### ISSUE TITLE
Errors thrown when switching buffers while yank is still highlighted

### ISSUE THREAD

**Issue by hupfdule** [machakann/vim-highlightedyank#39] opened 2019-04-15 08:22 UTC
When yanking some text and then switching buffer while the highlight is still active errors will be thrown. See below screenshots.

This one is shown while the the current buffer is still visible:

![yank](https://user-images.githubusercontent.com/36069345/56117291-0fedf000-5f68-11e9-9163-8a7fc73595dc.png)

This one is shown after the new buffer is visible. This one will be triggered endlessly! I didn't find a way to get rid of it other than closing vim completely.

![yank2](https://user-images.githubusercontent.com/36069345/56117385-3f9cf800-5f68-11e9-8645-6320aa5c44ff.png)

The examples above were taken withing neovim, but the problem occurs withing vim, too.

**Comment by machakann** [comment] 2019-06-06 12:29
Thank you for your report and sorry for my late response.

Could you paste the output of `:version` command?
It may help to debug.

**Comment by machakann** [comment] 2019-06-06 12:29
I tried the following steps but could not reproduce.
Please let me know if I misunderstand something.

1. Open vim.
1. Make two buffers. (buffer1 & buffer2)
1. Press `yy` to yank a line in buffer1
1. Press `CTRL-^` to switch to buffer2

![hy](https://user-images.githubusercontent.com/480049/59032817-c18b0c80-8899-11e9-9711-5295c0956398.gif)

**Comment by hupfdule** [comment] 2019-06-07 07:48
Hello,

yes, that steps you describe are the correct ones. 
Also it is important to execute Step 4 fast enough, so that the highlighted range is still highlighted.

However, I tried again with vim 8.1 and neovim 0.3.4, but I am also unable to reproduce this problem.
Maybe it was a conflict with another plugin that isn't activated in my current setup. I don't know.

Since I am not able to reproduce it myself, you can as well close this issue.

**Comment by machakann** [comment] 2019-06-07 08:26
OK, I will close this issue but feel free to re-open if you observe again.

**Closed as completed by machakann** 2019-06-07 08:26 UTC
